keys = (
    ("Astronomy",),
    ("Physics",),
    ("Biology",),
    ("Chemistry",),
    ("Neuroscience",),
    ("Genetics",),
    ("Planetary Science",),
    ("Physiology",),
    ("Evolution",),
    ("Cosmology",),
    ("Medicine",),
    ("Paleontology",),
    ("Relativity",),
    ("Materials Science",),
    ("Human Biology",),
    ("Planetary Physics",),
    ("Neurobiology",),
    ("Ecology",),
    ("Anatomy",),
    ("Geology",),
    ("Inorganic Chemistry",),
    ("Zoology",),
    ("Space Science",),
    ("Psychology",),
    ("Quantum Physics",),
    ("Neuroscience Research",),
    ("Evolutionary Biology",),
    ("Meteorology",),
    ("Botany",),
    ("Human Physiology",),
    ("Astrophysics",),
    ("Microbiology",),
    ("Oceanography",),
    ("Neuroplasticity",),
    ("Biochemistry",),
    ("Thermodynamics",),
    ("Zoology Research",),
    ("Anthropology",),
    ("Vision Science",),
    ("Cell Biology",),
    ("Astrobiology",),
    ("Environmental Science",),
    ("Human Anatomy",),
    ("Cognitive Science",),
    ("Physics Research",),
    ("Marine Biology",),
    ("Evolutionary Genetics",),
    ("Immunology",),
    ("Chronobiology",),
    ("Atmospheric Science",),
    ("Chemistry Research",),
    ("Robotics",),
    ("Cognitive Neuroscience",),
    ("Thermal Physics",),
    ("Biophysics",),
    ("Earth Science",),
    ("Neurochemistry",),
    ("Evolutionary Theory",),
    ("Optics",),
    ("Human Development",),
    ("Astrometry",),
    ("Ecophysiology",),
    ("Biotechnology",),
    ("Seismology",),
    ("Cognitive Psychology",),
    ("Molecular Biology",),
    ("Environmental Biology",),
    ("Physics of Fluids",),
    ("Human Metabolism",),
    ("Astrochemistry",),
    ("Behavioral Science",),
    ("Planetary Geology",),
    ("Biostatistics",),
    ("Cognitive Biology",),
    ("Evolutionary Anthropology",),
    ("Radiation Physics",),
    ("Systems Biology",),
    ("Environmental Chemistry",),
    ("Neural Engineering",),
    ("Comparative Anatomy",),
    ("Physics Measurement",),
)

values = [
    "Light from the Sun reaches Earth in about 8 minutes and 20 seconds.",
    "Absolute zero temperature is −273.15 degrees Celsius.",
    "The human body contains roughly as many bacterial cells as human cells.",
    "Water reaches its maximum density at 4 degrees Celsius.",
    "The human brain consumes about 20 percent of the body's energy.",
    "All humans share approximately 99.9 percent of their DNA.",
    "Jupiter has the strongest magnetic field of all planets in the Solar System.",
    "The human heart pumps around 7,000 liters of blood per day.",
    "Birds are direct descendants of theropod dinosaurs.",
    "The universe is expanding, and the expansion is accelerating.",
    "Antibiotics are ineffective against viruses.",
    "The oldest known fossils are over 3.5 billion years old.",
    "Time slows down at speeds close to the speed of light.",
    "Diamonds and graphite are made of the same element, carbon.",
    "Human skin renews itself approximately every 27 days.",
    "A day on Venus is longer than a year on Venus.",
    "The brain has more synaptic connections than stars in the Milky Way.",
    "Phytoplankton produces more than half of Earth's oxygen.",
    "Human bones are stronger than concrete by weight.",
    "Tectonic plates move at roughly the speed fingernails grow.",
    "Gold is highly resistant to corrosion and oxidation.",
    "Octopuses have three hearts.",
    "Sound cannot travel in space because there is no medium.",
    "The placebo effect can reduce pain through brain activity.",
    "Electrons do not orbit the nucleus like planets.",
    "The brain itself cannot feel pain.",
    "All mammals evolved from synapsid ancestors.",
    "Lightning can heat air to over 30,000 degrees Celsius.",
    "Plants can communicate using chemical signals.",
    "The liver can regenerate lost tissue.",
    "Neutron stars are so dense that a teaspoon would weigh billions of tons.",
    "Viruses are not considered living organisms by many scientists.",
    "More than 80 percent of the ocean remains unexplored.",
    "The brain can rewire itself throughout life.",
    "ATP is the primary energy currency of cells.",
    "Energy cannot be created or destroyed, only transformed.",
    "Dolphins use unique whistles to identify each other.",
    "Modern humans originated in Africa.",
    "Humans can distinguish millions of colors.",
    "Mitochondria have their own DNA.",
    "Extremophiles can survive in extreme temperatures and pressures.",
    "Carbon dioxide is a natural part of Earth's atmosphere.",
    "The smallest bone in the human body is the stapes in the ear.",
    "Memory is reconstructed, not replayed.",
    "Dark matter does not emit or absorb light.",
    "Blue whales are the largest animals to ever exist.",
    "Mutations are the primary source of genetic variation.",
    "Vaccines train the immune system without causing disease.",
    "Human circadian rhythms follow a roughly 24-hour cycle.",
    "Earth's atmosphere protects life from harmful radiation.",
    "pH measures the acidity or basicity of a solution.",
    "Robots can outperform humans in repetitive precision tasks.",
    "Sleep is critical for memory consolidation.",
    "Metals expand when heated due to increased atomic vibration.",
    "Proteins fold into specific shapes to function properly.",
    "Volcanoes release gases that shape Earth's atmosphere.",
    "Dopamine is involved in motivation and reward.",
    "Natural selection favors traits that increase reproduction.",
    "Light behaves as both a particle and a wave.",
    "The human brain continues developing into the mid-20s.",
    "Stars appear to move due to Earth's rotation.",
    "Humans can adapt to a wide range of climates.",
    "CRISPR allows precise gene editing.",
    "Earthquakes release energy stored in tectonic stress.",
    "Attention is a limited cognitive resource.",
    "RNA plays a key role in protein synthesis.",
    "Biodiversity increases ecosystem stability.",
    "Air resistance increases with velocity squared.",
    "The brain primarily uses glucose for energy.",
    "Organic molecules exist in interstellar space.",
    "Habits form through repeated neural pathways.",
    "Mars has the largest volcano in the Solar System.",
    "Correlation does not imply causation.",
    "Emotions influence decision-making processes.",
    "Tool use predates Homo sapiens.",
    "Not all radiation is harmful to humans.",
    "Biological systems emerge from complex interactions.",
    "Ozone protects life by absorbing ultraviolet radiation.",
    "Brain signals can control external devices.",
    "Vertebrates share a common skeletal blueprint.",
    "Measurement always introduces some uncertainty.",
              ]


facts_en = {key:value for key, value in zip(keys, values)}

